// templates/io-assist-react-editable/src/io-assist/components/threads/ThreadHistoryListItem.tsx
import React, { useRef, useEffect } from "react";

import { RESPONSE_STREAM_STATUS } from "../../types/stream";
import { IconButton } from "../shared/IconButton";
import { PencilIcon, TrashIcon, Spinner } from "../shared/icons";

type ThreadHistoryListItemProps = {
    threadId: string;
    title: string;
    isActive: boolean;
    isEditing: boolean;
    editValue: string;
    hasNotification: boolean;
    streamStatus?: string;
    onSelect: (threadId: string) => void;
    onStartEditing: (threadId: string, title: string, e: React.MouseEvent) => void;
    onCommitEdit: (threadId: string) => void;
    onEditChange: (value: string) => void;
    onEditKeyDown: (e: React.KeyboardEvent, threadId: string) => void;
    onDelete: (threadId: string, e: React.MouseEvent) => void;
};

export const ThreadHistoryListItem: React.FC<ThreadHistoryListItemProps> = ({
    threadId,
    title,
    isActive,
    isEditing,
    editValue,
    hasNotification,
    streamStatus,
    onSelect,
    onStartEditing,
    onCommitEdit,
    onEditChange,
    onEditKeyDown,
    onDelete,
}) => {
    const editRef = useRef<HTMLInputElement>(null);

    useEffect(() => {
        if (isEditing && editRef.current) {
            editRef.current.focus();
            editRef.current.select();
        }
    }, [isEditing]);

    const isThreadStreaming = streamStatus === RESPONSE_STREAM_STATUS.STREAMING;
    const showNotificationBadge = hasNotification && !isActive;
    const isThreadActionPending = isThreadStreaming;

    return (
        <div
            role="button"
            data-testid="thread-list-item"
            data-thread-id={threadId}
            data-active={isActive ? "true" : "false"}
            aria-current={isActive ? "true" : undefined}
            tabIndex={0}
            className={[
                "group flex flex-1 justify-start gap-2 px-4 h-8 rounded-md cursor-pointer hover:bg-thread-list-item-hover-background",
                isActive ? "bg-thread-list-item-hover-background" : "",
            ].join(" ")}
            onClick={() => !isEditing && onSelect(threadId)}
            onKeyUp={(e) => e.key === "Enter" && !isEditing && onSelect(threadId)}
        >
            <div className="flex items-center gap-2 cursor-pointer p-2 flex-1 min-w-0">
                {!isEditing && (
                    <div className={["flex items-center text-xs flex-1 min-w-0 overflow-hidden", isActive ? "text-text-states-active" : "text-text-default"].join(" ")}>
                        {showNotificationBadge && <span data-testid="thread-list-item-notification" className="size-2 rounded-full bg-orange-500 mr-2 flex-shrink-0" title="New response available" />}
                        <span className="truncate block" title={title}>
                            {title}
                        </span>
                        {isThreadActionPending && <Spinner className="ml-2 flex-shrink-0 size-5 " />}
                    </div>
                )}

                {isEditing && (
                    <input
                        ref={editRef}
                        data-testid="thread-rename-input"
                        aria-label="Rename thread"
                        className="flex-1 px-2 border border-border-default rounded text-text-default text-xs bg-transparent outline-none"
                        value={editValue}
                        onChange={(e) => onEditChange(e.target.value)}
                        onBlur={() => onCommitEdit(threadId)}
                        onKeyDown={(e) => onEditKeyDown(e, threadId)}
                        onClick={(e) => e.stopPropagation()}
                    />
                )}

                {/* Thread Action Buttons */}
                <div className={["gap-2 ml-auto items-center", isActive ? "flex" : "hidden group-hover:flex"].join(" ")}>
                    <IconButton size={12} tabIndex={isActive ? 0 : -1} title="Rename" disabled={isThreadActionPending} onClick={(e) => onStartEditing(threadId, title, e)}>
                        <PencilIcon />
                    </IconButton>
                    <IconButton size={12} tabIndex={isActive ? 0 : -1} title="Delete" disabled={isActive || isThreadActionPending} onClick={(e) => onDelete(threadId, e)}>
                        <TrashIcon />
                    </IconButton>
                </div>
            </div>
        </div>
    );
};

// templates/io-assist-angular-editable/src/app/io-assist/lib/components/threads/thread-history-list-item/thread-history-list-item.component.ts
import { CommonModule } from "@angular/common";
import { Component, computed, ElementRef, inject, input, InputSignal, Signal, signal, viewChild, WritableSignal } from "@angular/core";

import { AppIconComponent } from "../../../shared/components/app-icon/app-icon.component";
import { APP_ICON_SIZES, APP_ICON_VARIANTS } from "../../../shared/components/app-icon/enum";
import { AppSpinnerComponent } from "../../../shared/components/app-spinner/app-spinner.component";
import { APP_SPINNER_COMPONENT_SIZE } from "../../../shared/components/app-spinner/enum";
import { UI_STRINGS } from "../../../shared/constants/ui-strings";
import { ComponentEffectManagerService as EffectService } from "../../../shared/services/component-effect-manager/component-effect-manager.service";
import { OverlayService } from "../../../shared/services/overlay/overlay.service";
import { ResponsiveUIService } from "../../../shared/services/responsive-ui/responsive-ui.service";
import { MessageFacade } from "../../../shared/store/message/message.facade";
import { ResponseStreamFacade } from "../../../shared/store/response-stream/response-stream.facade";
import { THREAD_STATE } from "../../../shared/store/thread/enums";
import { ThreadFacade } from "../../../shared/store/thread/thread.facade";
import { UIThread } from "../../../shared/store/thread/types";

const COMPONENTS = [AppSpinnerComponent, AppIconComponent];
const MODULES = [CommonModule];

@Component({
    selector: "thread-history-list-item",
    templateUrl: "./thread-history-list-item.component.html",
    imports: [...MODULES, ...COMPONENTS],
    providers: [
        {
            provide: EffectService,
            useFactory: () => new EffectService("ThreadHistoryListItemComponent"),
        },
    ],
})
export class ThreadHistoryListItemComponent {
    protected readonly UI_STRINGS = UI_STRINGS.GENERAL;
    protected readonly APP_SPINNER_COMPONENT_SIZE = APP_SPINNER_COMPONENT_SIZE;
    protected readonly THREAD_STATE = THREAD_STATE;
    protected readonly APP_ICON_VARIANTS = APP_ICON_VARIANTS;
    protected readonly APP_ICON_SIZES = APP_ICON_SIZES;

    public readonly thread: InputSignal<UIThread> = input.required();
    protected isEditModeEnabled: WritableSignal<boolean> = signal<boolean>(false);

    protected threadNameInput: Signal<ElementRef | undefined> = viewChild<ElementRef | undefined>("threadNameInput");

    // Provided in root
    private readonly _threadFacade: ThreadFacade = inject(ThreadFacade);
    private readonly _messageFacade: MessageFacade = inject(MessageFacade);
    private readonly _responseStreamFacade: ResponseStreamFacade = inject(ResponseStreamFacade);
    private readonly _overlayService: OverlayService = inject(OverlayService);
    private readonly _responsiveUIService: ResponsiveUIService = inject(ResponsiveUIService);

    // Provided in current component
    private readonly _effectService: EffectService = inject(EffectService);

    protected readonly activeThreadId: Signal<string | null> = this._threadFacade.activeThreadId;

    private readonly _streamingThreadIds: Signal<Set<string>> = this._responseStreamFacade.streamingThreadIds;
    private readonly _threadsWithNotification: Signal<string[]> = this._responseStreamFacade.threadsWithCompletionNotification;

    protected readonly isThreadStreaming: Signal<boolean> = computed(() => {
        return this._streamingThreadIds().has(this.thread().id);
    });

    protected readonly hasCompletionNotification: Signal<boolean> = computed(() => {
        return this._threadsWithNotification().includes(this.thread().id);
    });

    constructor() {
        this.registerEffects();
    }

    protected handleEditModeEnable(): void {
        this.isEditModeEnabled.set(true);
    }

    protected handleEditModeDisable(): void {
        this.isEditModeEnabled.set(false);
    }

    protected handleRenameOnBlur(newName: string): void {
        // isEditModeEnabled is set to false synchronously by handleEditModeDisable() before
        // Angular removes the input from the DOM. Removing a focused input fires blur, so
        // checking the signal here lets us skip the rename when Escape (or Enter) already
        // called handleEditModeDisable() — the blur is just an artifact of DOM removal.
        if (!this.isEditModeEnabled()) return;
        this.handleEditModeDisable();
        this.onRenameThread(newName);
    }

    protected handleThreadSelection(): void {
        if (this.isEditModeEnabled()) return;

        const threadId: string = this.thread().id;

        this._responseStreamFacade.dispatchClearCompletionNotification(threadId);

        if (threadId === this.activeThreadId()) {
            return this.handleThreadHistoryHide();
        }

        this._threadFacade.dispatchChangeActiveThread(threadId);
        this._messageFacade.dispatchFetchMessagesFromThread(this.thread());

        this.handleThreadHistoryHide();
    }

    private handleThreadHistoryHide(): void {
        if (!this._responsiveUIService.isSmDown) {
            return;
        }

        this._overlayService.isThreadHistoryDisplayed.set(false);
    }

    protected onRenameThread(newName: string): void {
        if (newName.trim() === "" || newName === this.thread().title) return;

        this._threadFacade.dispatchRenameThread(this.thread(), newName);
    }

    protected onDeleteThread(thread: UIThread): void {
        this._threadFacade.dispatchDeleteThread(thread);
    }

    private registerEffects(): void {
        this._effectService.registerEffect("ThreadHistoryListItem.focusThreadNameInput.on.isEditModeEnabled", () => this.isEditModeEnabled() && this.threadNameInput()?.nativeElement.focus());
    }
}

@let isCurrentlyActive = activeThreadId() === thread().id;
@let isTryingToDeleteThread = thread().state === THREAD_STATE.DELETING;
@let isTryingToRenameThread = thread().state === THREAD_STATE.RENAMING;
@let isThreadActionPending = isThreadStreaming() || isTryingToDeleteThread || isTryingToRenameThread;
@let hasNotification = hasCompletionNotification();
@let showNotificationBadge = hasNotification && !isCurrentlyActive;

<div
    data-testid="thread-list-item"
    class="flex flex-1 justify-start gap-2 px-4 h-8 rounded-md hover:bg-thread-list-item-hover-background group"
    tabindex="0"
    [ngClass]="{
        'bg-thread-list-item-hover-background': isCurrentlyActive,
    }"
    (keyup.enter)="handleThreadSelection()"
    (click)="handleThreadSelection()"
>
    <div class="flex items-center gap-2 cursor-pointer p-2 flex-1 min-w-0">
        @if (!isEditModeEnabled()) {
            <div
                class="flex items-center text-xs text-text-default flex-1 min-w-0 overflow-hidden"
                [ngClass]="{
                    'text-text-states-active': isCurrentlyActive,
                }"
            >
                @if (showNotificationBadge) {
                    <span data-testid="thread-list-item-notification" class="w-2 h-2 rounded-full bg-orange-500 mr-2 flex-shrink-0" title="New response available"></span>
                }

                <span class="truncate block" [attr.title]="thread().title">
                    {{ thread().title }}
                </span>

                @if (isThreadActionPending) {
                    <app-spinner data-testid="thread-list-item-spinner" class="pl-2 flex-shrink-0" tabindex="-1" [size]="APP_SPINNER_COMPONENT_SIZE.SMALL"></app-spinner>
                }
            </div>
        }

        @if (isEditModeEnabled()) {
            <input
                #threadNameInput
                data-testid="thread-name-input"
                class="flex-1 px-2 border border-proto-border-default rounded text-proto-text-default"
                [value]="thread().title"
                (blur)="handleRenameOnBlur(threadNameInput.value)"
                (keydown.enter)="handleEditModeDisable(); onRenameThread(threadNameInput.value)"
                (keydown.escape)="handleEditModeDisable(); $event.stopPropagation()"
            />
        }

        <!-- Thread Action Buttons -->
        <div class="hidden group-hover:flex gap-2 ml-auto" [ngClass]="{ flex: isCurrentlyActive, hidden: !isCurrentlyActive }">
            <app-icon
                data-testid="thread-edit-button"
                [variant]="APP_ICON_VARIANTS.EDIT"
                [tabIndex]="isCurrentlyActive ? 0 : -1"
                [size]="APP_ICON_SIZES.S"
                [isDisabled]="isThreadActionPending"
                (onClick)="handleEditModeEnable()"
            />
            <app-icon
                data-testid="thread-delete-button"
                [variant]="APP_ICON_VARIANTS.DELETE"
                [tabIndex]="isCurrentlyActive ? 0 : -1"
                [size]="APP_ICON_SIZES.S"
                [isDisabled]="isCurrentlyActive || isThreadActionPending"
                (onClick)="onDeleteThread(thread()); $event.stopPropagation()"
            />
        </div>
    </div>
</div>
