// templates/io-assist-angular-editable/src/app/io-assist/lib/components/header/header.component.ts
import { CommonModule } from "@angular/common";
import { Component, inject, OnInit, Signal, WritableSignal } from "@angular/core";

import { APP_BUTTON_TYPES } from "../../shared/components/app-button/enum";
import { AppIconComponent } from "../../shared/components/app-icon/app-icon.component";
import { APP_ICON_SIZES, APP_ICON_VARIANTS } from "../../shared/components/app-icon/enum";
import { PANEL_BUTTON_ACTION_TYPE } from "../../shared/components/app-panel/enums";
import { APP_SPINNER_COMPONENT_SIZE } from "../../shared/components/app-spinner/enum";
import { AppTooltipComponent } from "../../shared/components/app-tooltip/app-tooltip.component";
import { TOOLTIP_POSITIONS } from "../../shared/components/app-tooltip/enum";
import { UI_STRINGS } from "../../shared/constants/ui-strings";
import { AnimationType } from "../../shared/directives/animation-effect/animation-type.enum";
import { OverlayService } from "../../shared/services/overlay/overlay.service";
import { MessageFacade } from "../../shared/store/message/message.facade";
import { ResponseStreamFacade } from "../../shared/store/response-stream/response-stream.facade";
import { ThreadFacade } from "../../shared/store/thread/thread.facade";
import { WorkingContextFacade } from "../../shared/store/working-context/working-context.facade";
import { WorkingContextPanelComponent } from "../working-context-panel/working-context-panel.component";

const MODULES = [CommonModule];
const COMPONENTS = [AppIconComponent, AppTooltipComponent];

@Component({
    selector: "header",
    templateUrl: "./header.component.html",
    imports: [...MODULES, ...COMPONENTS],
    providers: [WorkingContextFacade],
    host: {
        style: "display: flex; width: 100%;",
    },
})
export class HeaderComponent implements OnInit {
    protected readonly APP_SPINNER_COMPONENT_SIZE = APP_SPINNER_COMPONENT_SIZE;
    protected readonly UI_STRINGS = UI_STRINGS;
    protected readonly APP_ICON_VARIANTS = APP_ICON_VARIANTS;
    protected readonly APP_ICON_SIZES = APP_ICON_SIZES;
    protected readonly AnimationType = AnimationType;
    protected readonly TOOLTIP_POSITIONS = TOOLTIP_POSITIONS;

    // Provided in root
    private readonly _overlayService: OverlayService = inject(OverlayService);
    private readonly _threadFacade: ThreadFacade = inject(ThreadFacade);
    private readonly _responseStreamFacade: ResponseStreamFacade = inject(ResponseStreamFacade);

    // Provided by parent component
    private readonly _messageFacade: MessageFacade = inject(MessageFacade);

    // Provided in this component
    private readonly _workingContextFacade: WorkingContextFacade = inject(WorkingContextFacade);

    protected readonly isThreadHistoryDisplayed: WritableSignal<boolean> = this._overlayService.isThreadHistoryDisplayed;
    protected readonly isLoadingMessages: Signal<boolean> = this._messageFacade.isLoadingMessages;
    protected readonly messageLength: Signal<number> = this._messageFacade.messageLength;
    protected readonly isWorkingContextEnabled: Signal<boolean> = this._workingContextFacade.isWorkingContextEnabled;
    protected readonly hasAnyCompletionNotification: Signal<boolean> = this._responseStreamFacade.hasAnyCompletionNotification;

    public ngOnInit(): void {
        this._workingContextFacade.dispatchFetchIsWorkingContextEnabled();
    }

    protected displayThreadHistory(): void {
        this._overlayService.isThreadHistoryDisplayed.set(true);
    }

    protected displayHome(): void {
        this._messageFacade.dispatchClearMessages();

        this._threadFacade.dispatchChangeActiveThread(null);
    }

    protected handleWorkingContextPanelOpen(): void {
        this._overlayService.showPanelOverlay({
            title: UI_STRINGS.WORKING_CONTEXT_PANEL_COMPONENT.TITLE,
            content: WorkingContextPanelComponent,
            isHeaderCloseButtonDisplayed: true,
            footerButtons: [
                {
                    label: UI_STRINGS.GENERAL.CANCEL,
                    action: PANEL_BUTTON_ACTION_TYPE.CLOSE,
                    type: APP_BUTTON_TYPES.DEFAULT,
                    testId: "working-context-cancel-button",
                },
            ],
        });
    }
}

@let showHomeButton = isLoadingMessages() || messageLength() > 0;
@let showThreadPanelToggleButton = !isThreadHistoryDisplayed();
@let hasNotification = hasAnyCompletionNotification();

<div
    class="header"
    [ngClass]="{
        'flex flex-1 justify-start px-4 py-2 gap-2 self-stretch': true,
    }"
>
    @if (showThreadPanelToggleButton || showHomeButton) {
        <div
            [ngClass]="{
                flex: true,
            }"
        >
            @if (showThreadPanelToggleButton) {
                <div class="relative">
                    <app-icon data-testid="thread-toggle-button" [variant]="APP_ICON_VARIANTS.THREAD_HISTORY" (click)="displayThreadHistory()"></app-icon>

                    @if (hasNotification) {
                        <span class="absolute -top-1 -right-1 w-2.5 h-2.5 rounded-full bg-orange-500" title="New responses available"></span>
                    }
                </div>
            }

            @if (showHomeButton) {
                <app-tooltip [tooltipPosition]="TOOLTIP_POSITIONS.BOTTOM">
                    <app-icon tooltip-trigger data-testid="home-button" [variant]="APP_ICON_VARIANTS.HOME" (click)="displayHome()"></app-icon>
                    <span tooltip-content class="text-xs whitespace-nowrap">{{ UI_STRINGS.HEADER_COMPONENT.HOME_TOOLTIP }}</span>
                </app-tooltip>
            }
        </div>
    }

    <!-- Context Area -->
    @if (isWorkingContextEnabled()) {
        <app-tooltip [tooltipPosition]="TOOLTIP_POSITIONS.BOTTOM">
            <button
                tooltip-trigger
                data-testid="working-context-button"
                [ngClass]="{
                    'flex justify-center items-center px-2 py-[3.5px] border-[1px] rounded-[8px] text-text-default cursor-pointer': true,
                    'hover:text-text-states-hover hover:text-states-hover': true,
                    'font-weight-400 text-[10px] leading-[13px]': true,
                }"
                (click)="handleWorkingContextPanelOpen()"
            >
                {{ UI_STRINGS.WORKING_CONTEXT_PANEL_COMPONENT.VIEW_WORKING_CONTEXT_BUTTON }}
            </button>
            <span tooltip-content class="text-xs max-w-[260px] text-wrap">{{ UI_STRINGS.HEADER_COMPONENT.CONTEXT_TOOLTIP }}</span>
        </app-tooltip>
    }
</div>

// templates/io-assist-react-editable/src/io-assist/components/header/Header.tsx
import React from "react";

import { UI_STRINGS } from "../../constants/uiStrings";
import { useIoAssistStore } from "../../context/IoAssistContext";
import { useIoAiWebApi } from "../../hooks/useIoAiWebApi";
import { MESSAGES_LOADING_STATE } from "../../types/loading";
import { PANEL_CONTENT } from "../../types/panel";
import { IconButton } from "../shared/IconButton";
import { HomeIcon, ThreadHistoryIcon } from "../shared/icons";
import { Tooltip } from "../shared/Tooltip";

export const Header: React.FC = () => {
    const isThreadHistoryVisible = useIoAssistStore((s) => s.isThreadHistoryVisible);
    const messagesLength = useIoAssistStore((s) => s.messages.length);
    const messageLoadingState = useIoAssistStore((s) => s.messageLoadingState);
    const completionNotifications = useIoAssistStore((s) => s.completionNotifications);
    const isWorkingContextEnabled = useIoAssistStore((s) => s.isWorkingContextEnabled);
    const setIsThreadHistoryVisible = useIoAssistStore((s) => s.setIsThreadHistoryVisible);
    const setActivePanelContent = useIoAssistStore((s) => s.setActivePanelContent);
    const { newConversation } = useIoAiWebApi();

    const hasMessages = messagesLength > 0;
    const isMessageLoading = messageLoadingState.type === MESSAGES_LOADING_STATE.LOADING_RESPONSE || messageLoadingState.type === MESSAGES_LOADING_STATE.LOADING_FROM_THREAD;
    const hasNotification = completionNotifications.length > 0;
    const showThreadToggle = !isThreadHistoryVisible;
    const showHomeButton = isMessageLoading || hasMessages;

    const handleShowThreadHistory = () => {
        setIsThreadHistoryVisible(true);
    };

    const handleNewConversation = () => {
        void newConversation();
    };

    const handleWorkingContextOpen = () => {
        setActivePanelContent(PANEL_CONTENT.WORKING_CONTEXT);
    };

    return (
        <div data-testid="header" className="flex w-full items-center justify-start px-4 py-2 gap-2">
            {showThreadToggle || showHomeButton ? (
                <div className="flex">
                    {showThreadToggle && (
                        <div className="relative">
                            <IconButton size={12} containerSize={24} testId="thread-toggle-button" onClick={handleShowThreadHistory} title="Thread history">
                                <ThreadHistoryIcon />
                            </IconButton>
                            {hasNotification && <span className="absolute -top-1 -right-1 size-2.5 rounded-full bg-orange-500" />}
                        </div>
                    )}

                    {showHomeButton && (
                        <Tooltip position="bottom" content={UI_STRINGS.HEADER_COMPONENT.HOME_TOOLTIP}>
                            <IconButton
                                size={12}
                                containerSize={24}
                                testId="home-button"
                                onClick={handleNewConversation}
                                title="New conversation"
                                aria-label={UI_STRINGS.HEADER_COMPONENT.HOME_TOOLTIP}
                            >
                                <HomeIcon />
                            </IconButton>
                        </Tooltip>
                    )}
                </div>
            ) : null}

            {isWorkingContextEnabled && (
                <Tooltip position="bottom" content={<span className="max-w-[260px] text-wrap text-xs">{UI_STRINGS.HEADER_COMPONENT.CONTEXT_TOOLTIP}</span>}>
                    <button
                        type="button"
                        data-testid="working-context-button"
                        className="flex justify-center items-center px-2 py-[3.5px] border-[1px] rounded-[8px] text-text-default cursor-pointer hover:text-text-states-hover font-weight-400 text-[10px] leading-[13px]"
                        onClick={handleWorkingContextOpen}
                    >
                        {UI_STRINGS.WORKING_CONTEXT_PANEL_COMPONENT.VIEW_WORKING_CONTEXT_BUTTON}
                    </button>
                </Tooltip>
            )}
        </div>
    );
};
