// templates/io-assist-react-editable/src/io-assist/components/messages/ToolMessage.tsx
import React, { useMemo } from "react";

import { MdFormatter } from "./MdFormatter";
import { textToJSONMarkdown } from "./mdUtils";
import { UI_STRINGS } from "../../constants/uiStrings";
import { TOOL_RESULT_TYPES, type ToolResult, type UIToolMessage } from "../../types/message";
import { ChevronDownIcon, ChevronUpIcon, CircleFilledIcon, CircleOutlineIcon } from "../shared/icons";

type Props = {
    tool: UIToolMessage;
    parentToolTraceId: string;
    onToggle: (toolId: string, parentId: string) => void;
};

const parseTextResult = (result: ToolResult): unknown => {
    if (result.type !== TOOL_RESULT_TYPES.TEXT) return result;
    try {
        return { type: result.type, text: JSON.parse(result.text) };
    } catch {
        return { type: result.type, text: result.text };
    }
};

const resultToJSONMarkdown = (result: UIToolMessage["result"]): string => {
    if (result === undefined || result === null) return "No result available.";
    if (!Array.isArray(result)) return textToJSONMarkdown(parseTextResult(result));
    return result.map((r) => textToJSONMarkdown(parseTextResult(r))).join("\n\n---\n\n");
};

export const ToolMessage: React.FC<Props> = ({ tool, parentToolTraceId, onToggle }) => {
    const hasResult = tool.result !== undefined && tool.result !== null;
    const isExpanded = !!tool.isExpanded;

    const argsMd = useMemo(() => textToJSONMarkdown(tool.args ?? {}), [tool.args]);
    const resultMd = useMemo(() => resultToJSONMarkdown(tool.result), [tool.result]);

    return (
        <div data-testid="tool-message" className="flex flex-col justify-start py-2 px-[3px] text-[13px] font-weight-550 leading-[100%] text-text-states-active">
            <div className="flex items-center gap-2 px-1">
                <span
                    data-testid="tool-item-dot"
                    title={hasResult ? UI_STRINGS.TOOL_MESSAGE.TOOL_EXECUTION_SUCCESS : UI_STRINGS.TOOL_MESSAGE.TOOL_EXECUTION_PENDING}
                    className={["w-1.5 h-1.5 shrink-0 inline-flex items-center justify-center", hasResult ? "text-app-accent-color-1" : "text-text-states-active"].join(" ")}
                >
                    {hasResult ? <CircleFilledIcon /> : <CircleOutlineIcon />}
                </span>

                <button
                    type="button"
                    data-testid="tool-item-header"
                    className="tool-message__header flex flex-1 items-center cursor-pointer text-left"
                    onClick={() => onToggle(tool.id, parentToolTraceId)}
                >
                    <div className="flex flex-1 ps-2 items-center">{tool.toolName}</div>
                    <span className="size-3 shrink-0 inline-flex items-center justify-center">{isExpanded ? <ChevronUpIcon /> : <ChevronDownIcon />}</span>
                </button>
            </div>

            {isExpanded && (
                <div data-testid="tool-item-detail" className="tool-message__detail-pane flex flex-col gap-4 pt-2 px-2 w-full">
                    <div className="px-3 border-l border-text-default">
                        <div className="px-2 flex flex-col">
                            <span>Input</span>
                            <MdFormatter content={argsMd} />

                            <span>Output</span>
                            <MdFormatter content={resultMd} />
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

// templates/io-assist-angular-editable/src/app/io-assist/lib/components/messages/tool-message/tool-message.component.ts
import { CommonModule } from "@angular/common";
import { Component, inject, input, InputSignal } from "@angular/core";

import { AppIconComponent } from "../../../shared/components/app-icon/app-icon.component";
import { APP_ICON_SIZES, APP_ICON_VARIANTS } from "../../../shared/components/app-icon/enum";
import { AppMdFormatterComponent } from "../../../shared/components/app-md-formatter/app-md-formatter.component";
import { textToJSONMarkdown } from "../../../shared/components/app-md-formatter/utils";
import { UI_STRINGS } from "../../../shared/constants/ui-strings";
import { MessageFacade } from "../../../shared/store/message/message.facade";
import { TOOL_RESULT_TYPES, ToolResult, UIToolMessage } from "../../../shared/store/message/types";

const MODULES = [CommonModule];
const COMPONENTS = [AppIconComponent, AppMdFormatterComponent];

@Component({
    selector: "tool-message",
    templateUrl: "./tool-message.component.html",
    imports: [...MODULES, ...COMPONENTS],
    styleUrls: ["./tool-message.component.css"],
})
export class ToolMessageComponent {
    protected readonly APP_ICON_VARIANTS = APP_ICON_VARIANTS;
    protected readonly APP_ICON_SIZES = APP_ICON_SIZES;
    protected readonly UI_STRINGS = UI_STRINGS.TOOL_MESSAGE;

    public readonly message: InputSignal<UIToolMessage> = input.required<UIToolMessage>();
    public readonly parentToolTraceId: InputSignal<string> = input.required<string>();

    private readonly _messageFacade: MessageFacade = inject(MessageFacade);

    protected handleToggle(): void {
        this._messageFacade.dispatchToggleToolMessage(this.message().id, this.parentToolTraceId());
    }

    protected handleArgsToJSONMarkdown(): string {
        return textToJSONMarkdown(this.message().args);
    }

    protected handleResultToJSONMarkdown(): string {
        const result = this.message().result;

        if (!result) {
            return "No result available.";
        }

        if (!Array.isArray(result)) {
            const parsedResult = this.parseTextResultTextContent(result);

            return textToJSONMarkdown(parsedResult);
        }

        const parsedResults: ToolResult[] = result.map((res: ToolResult) => {
            if (res.type === TOOL_RESULT_TYPES.TEXT) {
                return this.parseTextResultTextContent(res);
            }

            /**
             *
             * TODO: Custom handling for other MCP result types: image, audio
             * For now, return as is:
             *
             * Image Content
             * {
             *   "type": "image",
             *   "data": "base64-encoded-image-data",
             *   "mimeType": "image/jpeg"
             * }
             *
             * Audio Content:
             * {
             *   "type": "audio",
             *   "data": "base64-encoded-audio-data",
             *   "mimeType": "audio/mpeg"
             * }
             */
            return res;
        });

        return parsedResults.map((res) => textToJSONMarkdown(res)).join("\n\n---\n\n");
    }

    private parseTextResultTextContent(result: ToolResult): ToolResult {
        let parsedText: unknown;

        if (result.type !== TOOL_RESULT_TYPES.TEXT) {
            return result;
        }

        if (result.type === TOOL_RESULT_TYPES.TEXT) {
            try {
                parsedText = JSON.parse(result.text as string);
                // eslint-disable-next-line unused-imports/no-unused-vars
            } catch (_unusedErr: unknown) {
                parsedText = result.text;
            }
        }

        return {
            type: result.type,
            text: parsedText,
        } as ToolResult;
    }
}

@let hasResult = message().result !== undefined && message().result !== null;
@let isExpanded = message().isExpanded !== undefined ? message().isExpanded : false;

<div
    class="tool-message-wrapper"
    data-testid="tool-message"
    [ngClass]="{
        'flex flex-col text-text-states-active justify-start py-2 px-[3px] text-[13px] font-weight-600 leading-[100%]': true,
    }"
>
    <div class="tool-message__header-wrapper" [ngClass]="{ 'flex items-center justify-center gap-2 px-1': true }">
        <app-icon
            data-testid="tool-item-dot"
            [title]="hasResult ? UI_STRINGS.TOOL_EXECUTION_SUCCESS : UI_STRINGS.TOOL_EXECUTION_PENDING"
            [iconFill]="hasResult ? '--app-accent-color-1' : 'text-text-states-active'"
            [hoverIconFill]="hasResult ? '--app-accent-color-1' : 'text-text-states-active'"
            [size]="APP_ICON_SIZES.XXXS"
            [variant]="hasResult ? APP_ICON_VARIANTS.CIRCLE_FILLED : APP_ICON_VARIANTS.CIRCLE_OUTLINE"
        ></app-icon>

        <div class="tool-message__header" data-testid="tool-item-header" tabindex="0" [ngClass]="{ 'flex flex-1 cursor-pointer': true }" (click)="handleToggle()" (keyup)="handleToggle()">
            <div class="flex flex-1 ps-2 items-center">
                {{ message().toolName }}
            </div>

            <app-icon [variant]="isExpanded ? APP_ICON_VARIANTS.CHEVRON_UP : APP_ICON_VARIANTS.CHEVRON_DOWN"></app-icon>
        </div>
    </div>

    @if (isExpanded) {
        <div
            class="tool-message__detail-pane"
            data-testid="tool-item-detail"
            [ngClass]="{
                'flex flex-col gap-4 list-none pt-2 px-2 w-full': true,
            }"
        >
            <div
                class="tool-message__detail-pane-section"
                [ngClass]="{
                    'px-3 border-l border-text-default': true,
                }"
            >
                <div class="tool-message__detail-pane-section-content" [ngClass]="{ 'px-2': true }">
                    <span>Input</span>
                    <app-md-formatter [content]="handleArgsToJSONMarkdown()"></app-md-formatter>

                    <span>Output</span>
                    <app-md-formatter [content]="handleResultToJSONMarkdown()"></app-md-formatter>
                </div>
            </div>
        </div>
    }
</div>
