// templates/io-assist-angular-editable/src/app/io-assist/lib/components/tool/tool-list-item/tool-list-item.component.ts
import { CommonModule } from "@angular/common";
import { Component, computed, inject, input, InputSignal, signal, Signal, WritableSignal } from "@angular/core";

import { ToolInfoComponent } from "./tool-info/tool-info.component";
import { AppIconComponent } from "../../../shared/components/app-icon/app-icon.component";
import { APP_ICON_SIZES, APP_ICON_VARIANTS } from "../../../shared/components/app-icon/enum";
import { APP_SPINNER_COMPONENT_SIZE } from "../../../shared/components/app-spinner/enum";
import { AppToggleComponent } from "../../../shared/components/app-toggle/app-toggle.component";
import { AppTooltipComponent } from "../../../shared/components/app-tooltip/app-tooltip.component";
import { TOOLTIP_POSITIONS } from "../../../shared/components/app-tooltip/enum";
import { UI_STRINGS } from "../../../shared/constants/ui-strings";
import { USER_TOOL_STATE } from "../../../shared/store/tool/enums";
import { ToolFacade } from "../../../shared/store/tool/tool.facade";
import { UITool } from "../../../shared/store/tool/types";

const COMPONENTS = [AppToggleComponent, AppIconComponent, AppTooltipComponent, ToolInfoComponent];
const MODULES = [CommonModule];

@Component({
    selector: "tool-list-item",
    templateUrl: "./tool-list-item.component.html",
    imports: [...COMPONENTS, ...MODULES],
    host: {
        "(mouseenter)": "handleMouseEnter()",
        "(mouseleave)": "handleMouseLeave()",
    },
})
export class ToolListItemComponent {
    public readonly tool: InputSignal<UITool> = input.required<UITool>();

    protected readonly APP_SPINNER_COMPONENT_SIZE = APP_SPINNER_COMPONENT_SIZE;
    protected readonly UI_STRINGS = UI_STRINGS.TOOL_LIST_ITEM_COMPONENT;
    protected readonly APP_ICON_VARIANTS = APP_ICON_VARIANTS;
    protected readonly APP_ICON_SIZES = APP_ICON_SIZES;
    protected readonly TOOLTIP_POSITIONS = TOOLTIP_POSITIONS;

    private readonly _toolFacade: ToolFacade = inject(ToolFacade);
    private readonly _enabledTools: Signal<UITool[]> = this._toolFacade.enabledTools;

    protected isHovered: WritableSignal<boolean> = signal<boolean>(false);

    protected readonly isEnabled: Signal<boolean> = computed<boolean>(() => this._enabledTools().includes(this.tool()));
    protected readonly isOperationPending: Signal<boolean> = computed<boolean>(() => this.tool().state !== USER_TOOL_STATE.IDLE);

    protected handleToolToggle(tool: UITool): void {
        return this._toolFacade.dispatchToggleTool(tool);
    }

    protected handleMouseEnter(): void {
        this.isHovered.set(true);
    }

    protected handleMouseLeave(): void {
        this.isHovered.set(false);
    }
}

@let toolName = tool().name;
<div
    data-testid="tool-list-item"
    class="flex justify-between content-center items-center px-2 py-1 gap-2 cursor-pointer rounded-md"
    tabindex="0"
    [ngClass]="{
        'hover:bg-app-background-secondary': isHovered(),
    }"
>
    <app-toggle data-testid="tool-toggle" [isChecked]="isEnabled()" (onToggle)="handleToolToggle(tool())" />

    <!-- Tool Title -->
    <span
        class="flex flex-1 text-text-default text-xs"
        [ngClass]="{
            'text-text-states-hover': isHovered(),
        }"
        >{{ toolName }}</span
    >

    <!-- Tool Info -->
    <app-tooltip [tooltipPosition]="TOOLTIP_POSITIONS.TOP">
        <app-icon
            tooltip-trigger
            data-testid="tool-info-icon"
            [variant]="APP_ICON_VARIANTS.INFO"
            [iconFill]="!isHovered() ? '--app-text-default' : '--app-text-states-active'"
            [hoverBackgroundColor]="'--app-icon-background-hover'"
            [size]="APP_ICON_SIZES.XS"
        ></app-icon>

        <tool-info tooltip-content [tool]="tool()"></tool-info>
    </app-tooltip>
</div>

// templates/io-assist-react-editable/src/io-assist/components/tool/ToolListItem.tsx
import React, { useState } from "react";

import type { UITool } from "../../types";
import { Icon } from "../shared/Icon";
import { InfoIcon } from "../shared/icons";
import { ToggleInput } from "../shared/ToggleInput";
import { Tooltip } from "../shared/Tooltip";

type Props = {
    tool: UITool;
    onToggle: (tool: UITool) => void;
};

export const ToolListItem: React.FC<Props> = ({ tool, onToggle }) => {
    const [isHovered, setIsHovered] = useState(false);

    return (
        <div
            data-testid="tool-list-item"
            data-tool-name={tool.name}
            className={["flex justify-between items-center px-2 py-1 gap-2 cursor-pointer rounded-md w-full", isHovered ? "bg-app-background-secondary" : ""].filter(Boolean).join(" ")}
            onMouseEnter={() => setIsHovered(true)}
            onMouseLeave={() => setIsHovered(false)}
        >
            <ToggleInput isChecked={tool.enabled} onToggle={() => onToggle(tool)} testId="tool-toggle" />

            <span className={["flex flex-1 text-xs", isHovered ? "text-text-states-hover" : "text-text-default"].join(" ")}>{tool.name}</span>

            <Tooltip
                content={
                    <div className="flex justify-center bg-app-background-secondary text-text-default border border-border-default p-4 rounded-md leading-[17px] text-xs min-w-[240px] max-w-[320px]">
                        <div>
                            <span className="text-text-states-active font-weight-600">Server name: </span>
                            {tool.mcpServerName}
                        </div>
                    </div>
                }
            >
                <span
                    className={["inline-flex items-center justify-center rounded-sm hover:bg-app-icon-background-hover", isHovered ? "text-text-states-active" : "text-text-default"].join(" ")}
                    aria-label="Tool info"
                >
                    <Icon size={12}>
                        <InfoIcon />
                    </Icon>
                </span>
            </Tooltip>
        </div>
    );
};
