// templates/io-assist-angular-editable/src/app/io-assist/lib/components/input-area/input-area.component.ts
import { CommonModule } from "@angular/common";
import { Component, computed, ElementRef, inject, Signal, signal, viewChild, WritableSignal, OnInit } from "@angular/core";

import { InputAreaActionBarComponent } from "./input-area-action-bar/input-area-action-bar.component";
import { InputAreaSendButtonComponent } from "./input-area-send-button/input-area-send-button.component";
import { UI_STRINGS } from "../../shared/constants/ui-strings";
import { AccentGradientBorderDirective } from "../../shared/directives/accent-gradient-border/accent-gradient-border.directive";
import { AnimationType } from "../../shared/directives/animation-effect/animation-type.enum";
import { ComponentEffectManagerService as EffectService } from "../../shared/services/component-effect-manager/component-effect-manager.service";
import { Prompt } from "../../shared/services/prompt/types";
import { MessageFacade } from "../../shared/store/message/message.facade";
import { UI_MESSAGE_ROLES, UIMessage, UIUserMessage } from "../../shared/store/message/types";
import { PromptFacade } from "../../shared/store/prompt/prompt.facade";

const COMPONENTS = [InputAreaActionBarComponent, InputAreaSendButtonComponent];
const DIRECTIVES = [AccentGradientBorderDirective];
const MODULES = [CommonModule];

@Component({
    selector: "input-area",
    templateUrl: "./input-area.component.html",
    styleUrl: "./input-area.component.css",
    imports: [...COMPONENTS, ...MODULES, ...DIRECTIVES],
    providers: [
        PromptFacade,
        {
            provide: EffectService,
            useFactory: () => new EffectService("InputAreaComponent"),
        },
    ],
})
export class InputAreaComponent implements OnInit {
    protected inputValue: WritableSignal<string> = signal<string>("");
    protected isAnimationComplete: WritableSignal<boolean> = signal<boolean>(false);

    protected readonly UI_STRINGS = UI_STRINGS.INPUT_COMPONENT;
    protected readonly AnimationType = AnimationType;
    protected readonly sendButton: Signal<InputAreaSendButtonComponent | undefined> = viewChild(InputAreaSendButtonComponent);
    protected readonly inputAreaRef: Signal<ElementRef | undefined> = viewChild<ElementRef>("inputTextArea");

    // Provided in current component
    private readonly _promptFacade: PromptFacade = inject(PromptFacade);
    private readonly _effectService: EffectService = inject(EffectService);

    // Provided by parent
    private readonly _messageFacade: MessageFacade = inject(MessageFacade);
    private readonly _userMessages: Signal<UIUserMessage[]> = computed<UIUserMessage[]>(() => {
        const allMessages: UIMessage[] = this._messageFacade.allMessages();

        return allMessages.filter((message: UIMessage) => message.role === UI_MESSAGE_ROLES.USER);
    });
    private readonly _currentUserMessage: WritableSignal<UIUserMessage | null> = signal<UIUserMessage | null>(null);

    private readonly _selectedPrompt: Signal<Prompt | null> = this._promptFacade.selectedPrompt;

    public ngOnInit(): void {
        this.registerEffects();
    }

    protected handleInputChange(event: Event): void {
        const target: HTMLTextAreaElement = event.target as HTMLTextAreaElement;

        this.setInputValue(target.value);
    }

    protected handleAnimationStart(): void {
        this.isAnimationComplete.set(false);
    }

    protected handleAnimationEnd(): void {
        this.isAnimationComplete.set(true);
    }

    protected setInputValue(value: string): void {
        this.inputValue.set(value);

        const shouldResetDefaultSize: boolean = value.trim() === "";

        // Use queueMicrotask to ensure textarea DOM updates are applied before calculating scrollHeight for resize
        queueMicrotask(() => this.resizeTextArea(shouldResetDefaultSize));
    }

    protected handleKeyDown(event: KeyboardEvent): void {
        if (event.key === "Enter" && event.shiftKey) {
            return;
        }

        if (event.key === "Enter") {
            // Prevent adding a new line
            event.preventDefault();

            // send message
            this.sendButton()?.handleSendMessage();
            return;
        }

        if (event.key === "ArrowUp" && event.shiftKey) {
            this.browseUserMessages("up");
        }

        if (event.key === "ArrowDown" && event.shiftKey) {
            this.browseUserMessages("down");
        }
    }

    private browseUserMessages(direction: "up" | "down"): void {
        const userMessages: UIUserMessage[] = this._userMessages();

        if (userMessages.length === 0) {
            return;
        }

        const currentMessage: UIUserMessage | null = this._currentUserMessage();

        const isAtFirstMessage: boolean = currentMessage?.id === this._userMessages()[0].id && direction === "up";

        if (isAtFirstMessage) {
            return;
        }

        const hasReachedLast: boolean = this._currentUserMessage()?.id === this._userMessages()[this._userMessages().length - 1].id && direction === "down";

        if (hasReachedLast) {
            return;
        }

        const currentMessageExists: boolean = currentMessage !== null && userMessages.some((msg: UIUserMessage) => msg.id === currentMessage.id);

        if (!currentMessageExists) {
            const index: number = direction === "up" ? userMessages.length - 1 : 0;

            this._currentUserMessage.set(userMessages[index]);

            return;
        }

        const currentMessageIndex: number = userMessages.findIndex((msg: UIUserMessage) => msg.id === currentMessage?.id);

        if (direction === "up") {
            const index: number = currentMessageIndex > 0 ? currentMessageIndex - 1 : 0;

            this._currentUserMessage.set(userMessages[index]);

            return;
        }

        const index: number = currentMessageIndex < userMessages.length - 1 ? currentMessageIndex + 1 : userMessages.length - 1;

        this._currentUserMessage.set(userMessages[index]);
    }

    private resizeTextArea(shouldResetDefault: boolean): void {
        const textarea: HTMLTextAreaElement | undefined = this.inputAreaRef()?.nativeElement;

        if (!textarea) {
            return;
        }

        textarea.style.height = "17px"; // Always reset to initial height

        if (!shouldResetDefault) {
            textarea.style.height = Math.min(textarea.scrollHeight, 260) + "px";

            return;
        }
    }

    private registerEffects(): void {
        this._effectService.registerEffect("InputArea.updatesInputValue.on.currentUserMessage", () => {
            const currentMessage = this._currentUserMessage();

            if (currentMessage === null) {
                return;
            }

            this.setInputValue(currentMessage.content || "");
        });

        this._effectService.registerEffect("InputArea.updatesInputValue.on.selectedPrompt", () => {
            const prompt = this._selectedPrompt();

            if (!prompt) return;

            const description = prompt?.description;

            if (description === undefined || description == null || description.trim() === "") {
                return;
            }

            this.setInputValue(description);

            this._promptFacade.dispatchClearSelectedPrompt();
        });
    }
}

<div
    class="input-area"
    data-testid="input-area"
    [ngClass]="{
        'w-full': true,
    }"
>
    <div
        class="input-area__container"
        [ngClass]="{
            relative: true,
        }"
    >
        <!-- Main input container -->
        <div
            class="input-area__content bg-app-background"
            [accentGradientBorder]="!isAnimationComplete()"
            [ngClass]="{
                'relative rounded-2xl': true,
            }"
        >
            <div
                [ngClass]="{
                    'flex flex-col gap-4 p-4 rounded-2xl': true,
                }"
            >
                <!-- Text input area -->
                <div
                    class="input-area__textarea-wrapper"
                    [ngClass]="{
                        'flex gap-3 items-start px-2': true,
                    }"
                >
                    <textarea
                        #inputTextArea
                        placeholder="{{ UI_STRINGS.INPUT_PLACEHOLDER }}"
                        data-testid="chat-input-field"
                        class="input-area__textarea"
                        rows="1"
                        [ngClass]="{
                            'flex-1 custom-scrollbar custom-scrollbar-snap-right text-text-default text-sm leading-4 h-auto min-h-[17px] max-h-[260px] resize-none border-none outline-none overflow-y-auto whitespace-pre-wrap': true,
                            'placeholder:text-text-states-default': true,
                            'hover:text-text-states-active': true,
                        }"
                        [value]="inputValue()"
                        (input)="handleInputChange($event)"
                        (keydown)="handleKeyDown($event)"
                    ></textarea>
                </div>
                <!-- Footer with toolbar and send button -->
                <div
                    class="input-area__footer"
                    [ngClass]="{
                        'flex gap-3 items-center justify-between': true,
                    }"
                >
                    <input-area-action-bar
                        [ngClass]="{
                            'flex-1': true,
                        }"
                    ></input-area-action-bar>

                    <input-area-send-button [userQuery]="inputValue()" (onSend)="setInputValue('')"></input-area-send-button>
                </div>
            </div>
        </div>
    </div>
</div>

// templates/io-assist-react-editable/src/io-assist/components/input-area/InputArea.tsx
import React, { useState, useRef, useCallback, useEffect, type KeyboardEvent, type ChangeEvent } from "react";

import { UI_STRINGS } from "../../constants/uiStrings";
import { useIoAssistStore } from "../../context/IoAssistContext";
import { useIoConnectApi } from "../../hooks/useIoConnectApi";
import { PERMISSION_MODE, type PermissionMode } from "../../stores/permission-mode";
import { UI_MESSAGE_ROLES } from "../../types/message";
import { PANEL_CONTENT } from "../../types/panel";
import type { SelectOption } from "../../types/select";
import { RESPONSE_STREAM_STATUS } from "../../types/stream";
import { Icon } from "../shared/Icon";
import { IconButton } from "../shared/IconButton";
import { ArrowUpIcon, PaperPlaneIcon, StopIcon, PromptPanelIcon, PromptPanelFilledIcon, ToolPanelIcon, ToolPanelFilledIcon } from "../shared/icons";
import { Select } from "../shared/Select";

const PERMISSION_OPTIONS: SelectOption<PermissionMode>[] = [
    {
        title: "Ask permissions",
        miniTitle: "Ask",
        description: "Always ask for action permissions",
        value: PERMISSION_MODE.ASK,
    },
    {
        title: "Auto accept permissions",
        miniTitle: "Auto",
        description: "Auto-approve all action permissions",
        value: PERMISSION_MODE.AUTO_ACCEPT,
    },
];

type Props = {
    onSend: (text: string) => void;
    onAbort: () => void;
    className?: string;
};

const MIN_HEIGHT = 17;
const MAX_HEIGHT = 260;

export const InputArea: React.FC<Props> = ({ onSend, onAbort, className }) => {
    const [inputValue, setInputValue] = useState("");
    const textareaRef = useRef<HTMLTextAreaElement>(null);
    const currentMsgIndexRef = useRef<number | null>(null);

    const isGenerating = useIoAssistStore((s) => {
        const id = s.activeThreadId;
        return !!id && s.streamsByThreadId[id]?.status === RESPONSE_STREAM_STATUS.STREAMING;
    });
    const messages = useIoAssistStore((s) => s.messages);
    const selectedPrompt = useIoAssistStore((s) => s.selectedPrompt);
    const setSelectedPrompt = useIoAssistStore((s) => s.setSelectedPrompt);

    const userMessages = messages.filter((m) => m.role === UI_MESSAGE_ROLES.USER);

    const updateValue = useCallback((value: string) => {
        setInputValue(value);

        requestAnimationFrame(() => {
            const el = textareaRef.current;
            if (!el) return;
            el.style.height = `${MIN_HEIGHT}px`;
            if (value.trim() !== "") {
                el.style.height = `${Math.min(el.scrollHeight, MAX_HEIGHT)}px`;
            }
        });
    }, []);

    const updateInputValue = (e: ChangeEvent<HTMLTextAreaElement>) => {
        updateValue(e.target.value);
        currentMsgIndexRef.current = null;
    };

    useEffect(() => {
        if (selectedPrompt?.description) {
            updateValue(selectedPrompt.description);
            setSelectedPrompt(null);
        }
    }, [selectedPrompt, updateValue, setSelectedPrompt]);

    const handleSend = useCallback(() => {
        const trimmed = inputValue.trim();
        if (!trimmed || isGenerating) return;

        onSend(trimmed);
        updateValue("");
        currentMsgIndexRef.current = null;
    }, [inputValue, isGenerating, onSend, updateValue]);

    const handleSendOrStop = useCallback(() => {
        if (isGenerating) {
            onAbort();
        } else {
            handleSend();
        }
    }, [isGenerating, onAbort, handleSend]);

    const handleKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
        if (e.key === "Enter" && !e.shiftKey) {
            e.preventDefault();
            handleSend();
            return;
        }

        if (e.key === "ArrowUp" && e.shiftKey) {
            e.preventDefault();
            browseMessages("up");
            return;
        }

        if (e.key === "ArrowDown" && e.shiftKey) {
            e.preventDefault();
            browseMessages("down");
            return;
        }
    };

    const browseMessages = (direction: "up" | "down") => {
        if (userMessages.length === 0) return;

        const currentMsgIndex = currentMsgIndexRef.current;
        let nextIndex: number;

        if (currentMsgIndex === null) {
            nextIndex = direction === "up" ? userMessages.length - 1 : 0;
        } else {
            if (direction === "up" && currentMsgIndex > 0) {
                nextIndex = currentMsgIndex - 1;
            } else if (direction === "down" && currentMsgIndex < userMessages.length - 1) {
                nextIndex = currentMsgIndex + 1;
            } else {
                return;
            }
        }

        currentMsgIndexRef.current = nextIndex;
        updateValue(userMessages[nextIndex].content ?? "");
    };

    const buttonState: "disabled" | "send" | "stop" = isGenerating ? "stop" : inputValue.trim().length > 0 ? "send" : "disabled";

    return (
        <div data-testid="input-area" className={["input-area w-full", className ?? ""].filter(Boolean).join(" ")}>
            <div className="input-area__container relative w-full">
                <div className="input-area__content accent-gradient-border relative rounded-2xl bg-app-background">
                    <div className="flex flex-col gap-4 p-4">
                        <div className="flex gap-3 items-start ps-[1px] pt-1">
                            <textarea
                                ref={textareaRef}
                                data-testid="chat-input-field"
                                aria-label={UI_STRINGS.INPUT_COMPONENT.INPUT_PLACEHOLDER}
                                placeholder={UI_STRINGS.INPUT_COMPONENT.INPUT_PLACEHOLDER}
                                rows={1}
                                className="flex-1 custom-scrollbar custom-scrollbar-no-gutter text-text-default text-sm leading-4 resize-none border-none outline-none overflow-y-auto whitespace-pre-wrap placeholder:text-text-states-disabled hover:text-text-states-active bg-transparent"
                                style={{
                                    height: `${MIN_HEIGHT}px`,
                                    minHeight: `${MIN_HEIGHT}px`,
                                    maxHeight: `${MAX_HEIGHT}px`,
                                }}
                                value={inputValue}
                                onChange={updateInputValue}
                                onKeyDown={handleKeyDown}
                            />
                        </div>

                        <div className="flex gap-3 items-center justify-between">
                            <ActionBar />

                            <button
                                type="button"
                                data-testid={buttonState === "stop" ? "chat-stop-button" : "chat-send-button"}
                                className={[
                                    "flex size-8 shrink-0 items-center justify-center rounded-full transition-colors",
                                    buttonState === "send" && "bg-app-accent-color-1 text-white cursor-pointer",
                                    buttonState === "stop" && "bg-app-accent-color-1 text-white cursor-pointer",
                                    buttonState === "disabled" && "bg-app-icon-background-disabled text-text-states-disabled cursor-not-allowed",
                                ]
                                    .filter(Boolean)
                                    .join(" ")}
                                onClick={handleSendOrStop}
                                disabled={buttonState === "disabled"}
                                title={buttonState === "stop" ? "Stop generation" : "Send message"}
                            >
                                <Icon
                                    className={["icon-wrapper", buttonState === "disabled" && "cursor-not-allowed"].filter(Boolean).join(" ")}
                                    size={buttonState === "stop" ? 14 : buttonState === "send" ? 18 : 16}
                                >
                                    {buttonState === "stop" ? <StopIcon /> : buttonState === "send" ? <ArrowUpIcon /> : <PaperPlaneIcon />}
                                </Icon>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

const ActionBar: React.FC = () => {
    const activePanelContent = useIoAssistStore((s) => s.activePanelContent);
    const setActivePanelContent = useIoAssistStore((s) => s.setActivePanelContent);
    const permissionMode = useIoAssistStore((s) => s.permissionMode);
    const { setPermissionMode } = useIoConnectApi();

    const [hovered, setHovered] = useState<"prompt" | "tool" | null>(null);

    const promptDisplayed = activePanelContent === PANEL_CONTENT.PROMPTS;
    const toolDisplayed = activePanelContent === PANEL_CONTENT.TOOLS;
    const promptFilled = promptDisplayed || hovered === "prompt";
    const toolFilled = toolDisplayed || hovered === "tool";

    return (
        <div className="flex flex-1 gap-1 items-center">
            <IconButton
                size={12}
                containerSize={24}
                testId="prompt-panel-button"
                shape="rounded-rectangle"
                aria-pressed={promptDisplayed}
                onClick={() => setActivePanelContent(PANEL_CONTENT.PROMPTS)}
                onMouseEnter={() => setHovered("prompt")}
                onMouseLeave={() => setHovered(null)}
                title="Browse prompts"
                aria-label="Browse prompts"
            >
                {promptFilled ? <PromptPanelFilledIcon /> : <PromptPanelIcon />}
            </IconButton>
            <IconButton
                size={12}
                containerSize={24}
                testId="tool-panel-button"
                shape="rounded-rectangle"
                aria-pressed={toolDisplayed}
                onClick={() => setActivePanelContent(PANEL_CONTENT.TOOLS)}
                onMouseEnter={() => setHovered("tool")}
                onMouseLeave={() => setHovered(null)}
                title="Manage tools"
                aria-label="Manage tools"
            >
                {toolFilled ? <ToolPanelFilledIcon /> : <ToolPanelIcon />}
            </IconButton>

            <div className="min-w-[63px]">
                <Select selectId="permission" options={PERMISSION_OPTIONS} value={permissionMode} onChange={(option) => void setPermissionMode(option.value)} preferredPlacement="above" />
            </div>
        </div>
    );
};
