// templates/io-assist-angular-editable/src/app/io-assist/lib/components/messages/assistant-message/assistant-message.component.ts
import { CommonModule } from "@angular/common";
import { Component, input, InputSignal } from "@angular/core";

import { AppMdFormatterComponent } from "../../../shared/components/app-md-formatter/app-md-formatter.component";
import { UIAssistantMessage } from "../../../shared/store/message/types";
import { MessageFooterComponent } from "../message-footer/message-footer.component";

const MODULES = [CommonModule];
const COMPONENTS = [AppMdFormatterComponent, MessageFooterComponent];

@Component({
    selector: "assistant-message",
    templateUrl: "./assistant-message.component.html",
    imports: [...MODULES, ...COMPONENTS],
})
export class AssistantMessageComponent {
    public readonly message: InputSignal<UIAssistantMessage> = input.required<UIAssistantMessage>();
}

@let shouldDisplayFooter = message().displayFooter && message().responseForUserQueryId && message().content !== "";

<div
    class="assistant-message"
    data-testid="assistant-message"
    [ngClass]="{
        'flex flex-col flex-1 min-w-0 max-w-full self-stretch text-text-states-active font-weight-400 leading-[19px] safe-word-break': true,
    }"
>
    <app-md-formatter [content]="message().content ?? ''"></app-md-formatter>

    @if (shouldDisplayFooter) {
        <message-footer [messageFooterId]="message().responseForUserQueryId ?? ''"></message-footer>
    }
</div>

// templates/io-assist-react-editable/src/io-assist/components/messages/AssistantMessage.tsx
import React from "react";

import { MdFormatter } from "./MdFormatter";
import { MessageFooter } from "./MessageFooter";
import type { UIAssistantMessage } from "../../types";

type Props = {
    message: UIAssistantMessage;
    showFooter?: boolean;
    /** Aggregated response text for the footer's copy button. */
    footerCopyText?: string;
    onReload?: () => void;
    isGenerating?: boolean;
};

export const AssistantMessage: React.FC<Props> = ({ message, showFooter = false, footerCopyText = "", onReload, isGenerating = false }) => {
    return (
        <div data-testid="assistant-message" className="flex flex-col flex-1 min-w-0 max-w-full self-stretch text-text-states-active font-weight-weight-400 leading-[19px] safe-word-break">
            {message.content && (
                <div data-testid="assistant-message-text">
                    <MdFormatter content={message.content} />
                </div>
            )}

            {showFooter && <MessageFooter copyText={footerCopyText} onReload={onReload} isGenerating={isGenerating} />}
        </div>
    );
};
